version: "3.8"
services:
  app:
    image: springboot-book-app
    build:
      context: .
    ports:
      - 8989-9000:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/dtodatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: priyanka
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: priyanka
      MYSQL_DATABASE: dtodatabase
    ports:
      - 3306-4000:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
